//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintServiceLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintServiceLibrary.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t access a specific registry key.
        /// </summary>
        public static string AccessRegistryKey {
            get {
                return ResourceManager.GetString("AccessRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding failure.
        /// </summary>
        public static string BindingFailure {
            get {
                return ResourceManager.GetString("BindingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to empty {0} template.
        /// </summary>
        public static string CannotBindToEmptyTemplate {
            get {
                return ResourceManager.GetString("CannotBindToEmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to empty ZPL template.
        /// </summary>
        public static string CannotBindToEmptyZPLTemplate {
            get {
                return ResourceManager.GetString("CannotBindToEmptyZPLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize empty JSON.
        /// </summary>
        public static string CannotDeserializeEmptyJson {
            get {
                return ResourceManager.GetString("CannotDeserializeEmptyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source is missing.
        /// </summary>
        public static string DataSourceIsNull {
            get {
                return ResourceManager.GetString("DataSourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print commands are empty. Nothing to print..
        /// </summary>
        public static string EmptyPrintCommands {
            get {
                return ResourceManager.GetString("EmptyPrintCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Query.
        /// </summary>
        public static string EmptyQuery {
            get {
                return ResourceManager.GetString("EmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to a designated printer.
        /// </summary>
        public static string ErrorConnectToDesignatedPrinter {
            get {
                return ResourceManager.GetString("ErrorConnectToDesignatedPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during printing. Error code.
        /// </summary>
        public static string ErrorOccuredDuringPrinting {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to read printer data.
        /// </summary>
        public static string ErrorReadPrinterAttempt {
            get {
                return ResourceManager.GetString("ErrorReadPrinterAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection string.
        /// </summary>
        public static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LPT port name.
        /// </summary>
        public static string InvalidLptPortName {
            get {
                return ResourceManager.GetString("InvalidLptPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Name, Baud Rate or Data Bits are in invalid format.
        /// </summary>
        public static string InvalidSerialData {
            get {
                return ResourceManager.GetString("InvalidSerialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value None is not valid for Stop Bit parameters.
        /// </summary>
        public static string InvalidStopBits {
            get {
                return ResourceManager.GetString("InvalidStopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML.
        /// </summary>
        public static string InvalidXML {
            get {
                return ResourceManager.GetString("InvalidXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ZPL structure. ZPL must start with ^XA and ends with ^XZ.
        /// </summary>
        public static string InvalidZPL {
            get {
                return ResourceManager.GetString("InvalidZPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Exception.
        /// </summary>
        public static string IOException {
            get {
                return ResourceManager.GetString("IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing JSON. Maybe incorrect JSON format?.
        /// </summary>
        public static string JsonParsingError {
            get {
                return ResourceManager.GetString("JsonParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Database source is missing DB Settings structure!.
        /// </summary>
        public static string MissingDBSetting {
            get {
                return ResourceManager.GetString("MissingDBSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Database source is missing DB Settings structure!.
        /// </summary>
        public static string MissingDBSettingStructure {
            get {
                return ResourceManager.GetString("MissingDBSettingStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command to execute.
        /// </summary>
        public static string NoCommandToExecute {
            get {
                return ResourceManager.GetString("NoCommandToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address or Network Port is not specified.
        /// </summary>
        public static string NoIpAddressOrPort {
            get {
                return ResourceManager.GetString("NoIpAddressOrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No USB Printer Found.
        /// </summary>
        public static string NoUsbPrinterFound {
            get {
                return ResourceManager.GetString("NoUsbPrinterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XML template.
        /// </summary>
        public static string NoXMLTemplate {
            get {
                return ResourceManager.GetString("NoXMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error printing document.
        /// </summary>
        public static string PrintError {
            get {
                return ResourceManager.GetString("PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer name is empty!.
        /// </summary>
        public static string PritnerNameEmpty {
            get {
                return ResourceManager.GetString("PritnerNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Error.
        /// </summary>
        public static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read request timed-out.
        /// </summary>
        public static string ReadRequestTimeOut {
            get {
                return ResourceManager.GetString("ReadRequestTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source contains more binding fields than data values.
        /// </summary>
        public static string SourceContainsMoreFields {
            get {
                return ResourceManager.GetString("SourceContainsMoreFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or Data is missing.
        /// </summary>
        public static string SourceOrDataMissing {
            get {
                return ResourceManager.GetString("SourceOrDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Error.
        /// </summary>
        public static string WriteError {
            get {
                return ResourceManager.GetString("WriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra printer connection failed.
        /// </summary>
        public static string ZebraConnectionFailed {
            get {
                return ResourceManager.GetString("ZebraConnectionFailed", resourceCulture);
            }
        }
    }
}
